### ISSUE TITLE
[Bug] Doesnt work on players

### ISSUE THREAD

**Issue by Theryk** [Voidmenull/DebuffTimers#1]
Hello, im using LunaUnitframes and it does work on mobs and 'Training Dummy' on RetroWoW but when i duel someone and dot him (with a warlock for example) the timers dont show.

Thanks

**Comment by Theryk** [comment]
Testes it on Nostalrius PVP on outdoor, does not work on enemy players in any way (not only in duels).

**Comment by Voidmenull** [comment]
yea, looks like i overseen the pvp part, will fix this soon :)

**Comment by Theryk** [comment]
Thanks you for your work :) i hope it's an easy fix!

**Comment by Theryk** [comment]
any news, @Voidmenull ?

**Comment by Voidmenull** [comment]
yes, hopefully ill be done tomorrow :) Its a lot of things i had to change..

**Comment by Theryk** [comment]
@Voidmenull Thanks you, im waiting impatientient. :)

**Comment by Voidmenull** [comment]
are you sure you used the newest version from github?

cant find the pvp bug, it worked for 2 other ppl so far

**Comment by Theryk** [comment]
https://github.com/Voidmenull/DebuffTimers/archive/master.zip

this one? dont work in outdoor nor in duels either :/ ill test it again later when i get online

**Comment by Voidmenull** [comment]
can you do me a favor and test the newest version? pls report the bugs here

http://en.file-upload.net/download-12186411/DebuffTimers.zip.html

to open the menu: /debufftimers

edit: delete the old folder :)

**Comment by Theryk** [comment]
It work flawless now! no more intercept bug and debuff works on enemy players! 💃

**Comment by Voidmenull** [comment]
ty :) i will upload this version (with few more bugfixes) tomorrow :)
