### ISSUE TITLE
Any possibility of adding back the bars now that Aurae is only a CC Tracker?

### ISSUE THREAD

**Issue by Larsy93** [Voidmenull/DebuffTimers#10]
Any possibility of adding back the bars (not only times on icons) now that Aurae is only a CC Tracker?

**Comment by Voidmenull** [comment]
sorry, i will not do that :/ DebuffTimers will now have own elements but it will stay a addition to existing frames

**Comment by Larsy93** [comment]
Bars attached to the existing frame.
