### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Oliveryo** [Voidmenull/DebuffTimers#3]
Possible to show timers on my own debuffs?

**Comment by Voidmenull** [comment]
well, usually that is be done by the unitframe that you are useing...i dont want to "interfere" the addons by build in such function :/ sorry

**Comment by Oliveryo** [comment]
Okay, Im using pfui and the addon shows timers on targets debuffs but not on my own

**Comment by Voidmenull** [comment]
im useing pfUI too and the debuff icons are pretty messy in there, its def. build in but they dont work as they should...
your best chance is to write a bug report @ https://github.com/shagu/pfUI

**Comment by Oliveryo** [comment]
okay thanks
