### ISSUE TITLE
DebuffTimers - Disables pfUI's bag when using it together with pfUI/ModUI

### ISSUE THREAD

**Issue by Steffen-Hadberg-Nielsen** [Voidmenull/DebuffTimers#7]
https://www.youtube.com/watch?v=ypy0D1Pk2AM

Addon links:
[pfUI](https://github.com/shagu/pfUI)
[modUI](https://github.com/obble/modui)

Strangely enough there's no errors at all

**Comment by Voidmenull** [comment]
soon TM :) will update the addon this week :)
